network={
    ssid="wTEC"
    key_mgmt=WPA-EAP
    eap=PEAP
    identity="javt2003@estudiantes.tec.cr"
    password="2021453583jA##"
    anonymous_identity="anonymous"
    phase2="auth=MSCHAPV2"
    ca_cert=""
    priority=10
}

network={
    ssid="FAM VT"
    psk="xtcv2731"
    priority=2
}

network={
    ssid="Nexxt_TNT"
    psk="xtcv2731"
    priority=1
}
network={
    ssid="Arroyo"
    psk="rutyjose8573"
    priority=1
}
network={
    ssid="MADARA"
    psk="mariana1970"
    priority=1
}
network={
    ssid="jose"
    psk="keylornavas"
    key_mgmt=WPA-PSK
}
network={
    ssid="E5576_4480"
    psk="N974E2ELnTH"
    priority=3
}

