network={
    ssid="FAM VT"
    psk="xtcv2731"
    priority=2
}

network={
    ssid="Nexxt_TNT"
    psk="xtcv2731"
    priority=1
}
network={
    ssid="Arroyo"
    psk="rutyjose8573"
    priority=1
}
network={
    ssid="MADARA"
    psk="mariana1970"
    priority=1
}


